name: gnome-tetravex
adopt-info: gnome-tetravex
summary: Reorder tiles to fit a square
description: |
  Each square piece has a number on each side. Position the pieces on the left
  side of the board so that the same numbers are next to each other. If the
  numbers don't match, you can't put the piece there. Move quickly: you're
  being timed!

  You can make the game easier or harder by changing the size of the board.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  gnome-tetravex:
    interface: dbus
    bus: session
    name: org.gnome.Tetravex

apps:
  gnome-tetravex:
    command: usr/bin/gnome-tetravex
    extensions: [ gnome-3-38 ]
    desktop: usr/share/applications/org.gnome.Tetravex.desktop

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  gnome-tetravex:
    after: [desktop-gnome-platform]
    source: https://gitlab.gnome.org/GNOME/gnome-tetravex.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.Tetravex$|Icon=${SNAP}/meta/gui/org.gnome.Tetravex.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Tetravex.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/hicolor/scalable/org.gnome.Tetravex.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-tetravex/current/usr]
    organize:
      snap/gnome-tetravex/current/usr: usr
    prime:
      - -usr/lib/*/libgtk*
